In [1]:
import numpy as np

In [8]:
#loc: среднее нормального распределения
#scale стандартное отклонение нормального распределения
X = np.random.normal(loc=1, scale=50, size=(1000, 5))
X

array([[  17.93850763,   98.98849906,  -16.05655764,  -16.67658749,
         -38.95743179],
       [  12.57960548,    7.22728695,  101.7945352 ,   14.49880012,
         -14.22826871],
       [ -23.70847369,   34.29419282,  -58.47575713,   15.87435773,
          -2.15142621],
       ..., 
       [ -57.34088527,   39.40986821,  -31.02975246,  -28.77243568,
          63.12438752],
       [  54.40704848,  -20.8280592 ,   63.79815958,  -16.89947703,
         -77.90869274],
       [   4.27922717,   34.39660492,    8.08957234,  -24.13858825,
          -3.59952131]])

In [9]:
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_2 = ((X - mean) / std)

X_2

array([[ 0.35971682,  2.03590071, -0.33840383, -0.33972074, -0.83225256],
       [ 0.24949946,  0.09923832,  2.05780811,  0.28493669, -0.31996617],
       [-0.49684304,  0.67049776, -1.20089387,  0.31249857, -0.06978375],
       ..., 
       [-1.18856601,  0.77846643, -0.6428469 , -0.58208377,  1.2824622 ],
       [ 1.1097709 , -0.49288261,  1.28524532, -0.34418675, -1.63916222],
       [ 0.0787843 ,  0.67265921,  0.1525483 , -0.48923593, -0.09978231]])

In [10]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [13]:
summ = np.sum(Z, axis=1)
print(np.nonzero(summ > 10))

(array([1, 4, 5], dtype=int64),)


In [19]:
eye_1 = np.eye(3)
eye_2 = np.eye(3)
eyes = np.vstack((eye_1, eye_2))
eyes

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [20]:
import pandas as pd

In [25]:
df = pd.read_csv('C:/Users/N1keFan/Desktop/Py/DataFrames/titanic(ML course).csv', index_col='PassengerId')

In [26]:
df.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [30]:
df['Sex'].value_counts()
#577 - M; 314-F

male      577
female    314
Name: Sex, dtype: int64

In [31]:
df['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [56]:
df['Survived'].mean()
#Доля выживших 38.38 %

0.3838383838383838

In [72]:
pclass = df['Pclass'].value_counts()
result = pclass[1] * 100 / (pclass[1] + pclass[2] + pclass[3])
result
#Доля Pclass == 1 из всех Pclass (24.24)

24.242424242424242

In [54]:
print(round(df['Age'].mean(), 5))
print(round(df['Age'].median(), 5))
#mean=28.69; median=28

29.69912
28.0


In [83]:
corr = df['SibSp'].corr(df['Parch'], method='pearson')
corr * 100
#Корреляция SibSp и Parch = 41.48

41.48376986201567

In [90]:
names = df[df['Sex'] == 'female']['Name'].apply(lambda full_name:
                                                full_name.split(',')[1].split()[1])
names.value_counts().head(5)

William      13
Anna          9
Mary          9
Elizabeth     6
Thomas        6
Name: Name, dtype: int64

In [89]:
df.head(2)

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   

             SibSp  Parch     Ticket     Fare Cabin Embarked  
PassengerId                                                   
1                1      0  A/5 21171   7.2500   NaN        S  
2                1      0   PC 17599  71.2833   C85        C